export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAILURE = 'ADD_POST_FAILURE';

export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILURE = 'GET_POSTS_FAILURE';

export const GET_DROPDOWN_DATA = 'GET_DROPDOWN_DATA';
export const GET_DROPDOWN_DATA_SUCCESS = 'GET_DROPDOWN_DATA_SUCCESS';

export const SOCIAL_LOGIN = 'SOCIAL_LOGIN';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAIL = 'SOCIAL_LOGIN_FAIL';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';

export const UPDATE_LIKE = 'UPDATE_LIKE';
export const UPDATE_LIKE_SUCCESS = 'UPDATE_LIKE_SUCCESS';

export const UPDATE_DISLIKE = 'UPDATE_DISLIKE';
export const UPDATE_DISLIKE_SUCCESS = 'UPDATE_DISLIKE_SUCCESS';

export const GET_MATCHES = 'GET_MATCHES';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
export const GET_MATCHES_FAIL = 'GET_MATCHES_FAIL';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const GET_EDIT_PROFILE = 'GET_EDIT_PROFILE';
export const GET_EDIT_PROFILE_SUCCESS = 'GET_EDIT_PROFILE_SUCCESS';
export const GET_EDIT_PROFILE_FAIL = 'GET_EDIT_PROFILE_FAIL';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const HOME_FILTER = 'HOME_FILTER';
export const HOME_FILTER_SUCCESS = 'HOME_FILTER_SUCCESS';
export const HOME_FILTER_FAIL = 'HOME_FILTER_FAIL';

export const LOADER_TRUE = 'LOADER_TRUE';
export const LOADER_FALSE = 'LOADER_FALSE';

export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL';

export const STAR_RATING = 'STAR_RATING';
export const STAR_RATING_SUCCESS = 'STAR_RATING_SUCCESS';
export const STAR_RATING_FAIL = 'STAR_RATING_FAIL';

export const DIARY_LIST = 'DIARY_LIST';
export const DIARY_LIST_SUCCESS = 'DIARY_LIST_SUCCESS';
export const DIARY_LIST_FAIL = 'DIARY_LIST_FAIL';

export const ADD_DIARY = 'ADD_DIARY';
export const ADD_DIARY_SUCCESS = 'ADD_DIARY_SUCCESS';
export const ADD_DIARY_FAIL = 'ADD_DIARY_FAIL';

export const SAVE_ALBUM = 'SAVE_ALBUM';
export const SAVE_ALBUM_SUCCESS = 'SAVE_ALBUM_SUCCESS';
export const SAVE_ALBUM_FAIL = 'SAVE_ALBUM_FAIL';

export const GET_ALBUM = 'GET_ALBUM';
export const GET_ALBUM_SUCCESS = 'GET_ALBUM_SUCCESS';
export const GET_ALBUM_FAIL = 'GET_ALBUM_FAIL';

export const ADD_FCM_TOKEN = 'ADD_FCM_TOKEN';
export const REMOVE_FCM_TOKEN = 'REMOVE_FCM_TOKEN';

export const GET_CHAT_LIST = 'GET_CHAT_LIST';
export const GET_CHAT_LIST_SUCCESS = 'GET_CHAT_LIST_SUCCESS';
export const GET_CHAT_LIST_FAIL = 'GET_CHAT_LIST_FAIL';

export const READ_CHAT = 'READ_CHAT';

export const GET_MESSAGE_HISTORY = 'GET_MESSAGE_HISTORY';
export const GET_MESSAGE_HISTORY_SUCCESS = 'GET_MESSAGE_HISTORY_SUCCESS';
export const GET_MESSAGE_HISTORY_FAIL = 'GET_MESSAGE_HISTORY_FAIL';

export const ON_SEND_MEESSAGE = 'ON_SEND_MEESSAGE';
export const IN_APP_CHAT = 'IN_APP_CHAT';

export const GET_PROFILE_STATS = 'GET_PROFILE_STATS';
export const GET_PROFILE_STATS_SUCCESS = 'GET_PROFILE_STATS_SUCCESS';
export const GET_PROFILE_STATS_FAIL = 'GET_PROFILE_STATS_FAIL';

export const GET_VIDEO_CALL_TOKEN = 'GET_VIDEO_CALL_TOKEN';
export const GET_VIDEO_CALL_TOKEN_SUCCESS = 'GET_VIDEO_CALL_TOKEN_SUCCESS';

export const ACCEPT_CALL = 'ACCEPT_CALL';
export const DECLINE_CALL = 'DECLINE_CALL';
export const CALL_ENDED = 'CALL_ENDED';

//Flags callAcceptIsActive
export const CALL_ACCEPT_IS_ACTIVE = 'CALL_ACCEPT_IS_ACTIVE';
export const CALL_REJECT_IS_ACTIVE = 'CALL_REJECT_IS_ACTIVE';
export const CALL_ENDED_IS_ACTIVE = 'CALL_ENDED_IS_ACTIVE';
export const GET_ALL_STORIES = 'GET_ALL_STORIES';
export const GET_ALL_STORIES_SUCCESS = 'GET_ALL_STORIES_SUCCESS';

export const GET_ALL_STORIESFAIL = 'GET_ALL_STORIESFAIL';
export const VALIDATE_EMAIL = 'VALIDATE_EMAIL';
export const VALIDATE_EMAIL_SUCCESS = 'VALIDATE_EMAIL_SUCCESS';

// user report data

export const GET_USER_REPORT_DATA_SUCCESS = 'GET_USER_REPORT_DATA_SUCCESS';
export const GET_USER_REPORT_DATA = 'GET_USER_REPORT_DATA';
export const GET_USER_REPORT_DATA_FAIL = 'GET_USER_REPORT_DATA_FAIL';

// add user report data

export const ADD_USER_REPORT_DATA_SUCCESS = 'ADD_USER_REPORT_DATA_SUCCESS';
export const ADD_USER_REPORT_DATA = 'GET_USERADDPORT_DATA';
export const ADD_USER_REPORT_DATA_FAIL = 'GETADDER_REPORT_DATA_FAIL';

// add story

export const ADD_STORY_SUCCESS = 'ADD_STORY_SUCCESS';
export const ADD_STORY = 'ADD_STORY';
export const ADD_STORY_FAIL = 'ADD_STORY_FAIL';

// get Stories

export const GET_STORY_SUCCESS = 'GET_STORY_SUCCESS';
export const GET_STORY = 'GET_STORY';
export const GET_STORY_FAIL = 'GET_STORY_FAIL';

export const UPDATE_ALBUM_ACTIVE = 'UPDATE_ALBUM_ACTIVE';
export const UPDATE_ALBUM_ACTIVE_SUCCESS = 'UPDATE_ALBUM_ACTIVE_SUCCESS';
export const UPDATE_ALBUM_ACTIVE_FAIL = 'UPDATE_ALBUM_ACTIVE_FAIL';

export const GENERATE_ALBUM_CODE = 'GENERATE_ALBUM_CODE';
export const GENERATE_ALBUM_CODE_SUCCESS = 'GENERATE_ALBUM_CODE_SUCCESS';
export const GENERATE_ALBUM_CODE_FAIL = 'GENERATE_ALBUM_CODE_FAIL';

export const APPLY_ALBUM_CODE = 'APPLY_ALBUM_CODE';
export const APPLY_ALBUM_CODE_SUCCESS = 'APPLY_ALBUM_CODE_SUCCESS';
export const APPLY_ALBUM_CODE_FAIL = 'APPLY_ALBUM_CODE_FAIL';

// Live streams constants

export const GET_LIVE_STREAM = 'GET_LIVE_STREAM';
export const GET_LIVE_STREAM_SUCCESS = 'GET_LIVE_STREAM_SUCCESS';

export const CREATE_LIVE_STREAM = 'CREATE_LIVE_STREAM';
export const CREATE_LIVE_STREAM_SUCCESS = 'CREATE_LIVE_STREAM_SUCCESS';

export const START_NEW_STREAM = 'START_NEW_STREAM';
export const START_NEW_STREAM_SUCCESS = 'START_NEW_STREAM_SUCCESS';

export const JOIN_STREAM = 'JOIN_STREAM';
export const JOIN_STREAM_SUCCESS = 'JOIN_STREAM_SUCCESS';

export const END_STREAM = 'END_STREAM';
export const END_STREAM_SUCCESS = 'END_STREAM_SUCCESS';
